export const GET_SEARCH_CITY = "GET_SEARCH_CITY";
export const SET_SEARCH_CITY_RESULT = "SET_SEARCH_CITY_RESULT";
export const SET_SEARCH_CITY_ERROR = "SET_SEARCH_CITY_ERROR";

export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";